import { defineConfig, devices } from '@playwright/test';

const BASE_URL = process.env.BASE_URL ?? 'http://localhost:3000';

/**
 * A11y config: runs axe-core accessibility checks via Playwright.
 *
 * - No auth setup needed for public pages; authenticated paths use
 *   storage state generated by the E2E global setup step.
 * - Violations at "critical" or "serious" impact level cause test failure.
 * - "moderate" and "minor" violations are reported but do not block.
 * - Reports land in axe-reports/ which is git-ignored.
 */
export default defineConfig({
  testDir: './specs',
  timeout: 30_000,
  expect: { timeout: 5_000 },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: [
    ['html', { outputFolder: 'axe-reports/html', open: 'never' }],
    ['list'],
    ...(process.env.PW_JSON_REPORT_FILE
      ? [['json', { outputFile: process.env.PW_JSON_REPORT_FILE }] as const]
      : []),
  ],
  use: {
    baseURL: BASE_URL,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },
  webServer: {
    command: process.env.CI
      ? 'npm run seed --workspace=web && npm run start --workspace=web'
      : 'npm run dev --workspace=web',
    cwd: '../../',
    url: BASE_URL,
    env: {
      ...process.env,
      NEXTAUTH_URL: BASE_URL,
      NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET || 'playwright-local-secret',
    },
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    stdout: 'ignore',
    stderr: 'pipe',
  },
  projects: [
    {
      name: 'a11y-chrome',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
