import { test } from '@playwright/test';
import { checkA11y } from '../utils/axe';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Axe checks for authenticated user pages.
 * Requires storage state generated by the E2E setup project.
 * Run `npm run test:e2e --project=setup` once before running a11y checks
 * against authenticated routes, or use the combined CI pipeline which
 * generates storage state automatically.
 */

const AUTH_STATE = path.resolve(__dirname, '../../../tests/.auth/user.json');
const ADMIN_STATE = path.resolve(__dirname, '../../../tests/.auth/admin.json');

test.describe('A11y — Authenticated user pages', () => {
  test.use({
    storageState: fs.existsSync(AUTH_STATE) ? AUTH_STATE : undefined,
  });

  test('orders history page has no critical or serious violations', async ({ page }) => {
    await page.goto('/orders');
    await page.waitForLoadState('networkidle');
    await checkA11y(page);
  });

  test('profile page has no critical or serious violations', async ({ page }) => {
    await page.goto('/profile');
    await page.waitForLoadState('networkidle');
    await checkA11y(page);
  });
});

test.describe('A11y — Admin pages', () => {
  test.use({
    storageState: fs.existsSync(ADMIN_STATE) ? ADMIN_STATE : undefined,
  });

  test('admin orders page has no critical or serious violations', async ({ page }) => {
    await page.goto('/admin/orders');
    await page.waitForLoadState('networkidle');
    await checkA11y(page);
  });
});
