import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Axe checks for authenticated user pages.
 * Requires .auth/user.json generated by the E2E setup project.
 * Run `npm run test:e2e --project=setup` once before running a11y checks
 * against authenticated routes, or use the combined CI pipeline which
 * generates storage state automatically.
 */

const AUTH_STATE = path.resolve(__dirname, '../../../tests/.auth/user.json');

async function checkA11y(page: Parameters<typeof AxeBuilder>[0]['page']) {
  const results = await new AxeBuilder({ page })
    .withTags(['wcag2a', 'wcag2aa', 'wcag21aa'])
    .analyze();

  const blocking = results.violations.filter(
    (v) => v.impact === 'critical' || v.impact === 'serious'
  );

  if (blocking.length > 0) {
    const summary = blocking
      .map(
        (v) => `[${v.impact?.toUpperCase()}] ${v.id}: ${v.description} (${v.nodes.length} node(s))`
      )
      .join('\n');
    expect(blocking, `Blocking a11y violations found:\n${summary}`).toHaveLength(0);
  }
}

test.describe('A11y — Authenticated user pages', () => {
  test.use({
    storageState: fs.existsSync(AUTH_STATE) ? AUTH_STATE : undefined,
  });

  test('orders history page has no critical or serious violations', async ({ page }) => {
    await page.goto('/orders');
    await page.waitForLoadState('networkidle');
    await checkA11y(page);
  });

  test('profile page has no critical or serious violations', async ({ page }) => {
    await page.goto('/profile');
    await page.waitForLoadState('networkidle');
    await checkA11y(page);
  });
});

test.describe('A11y — Admin pages', () => {
  test.use({
    storageState: fs.existsSync(path.resolve(__dirname, '../../../tests/.auth/admin.json'))
      ? path.resolve(__dirname, '../../../tests/.auth/admin.json')
      : undefined,
  });

  test('admin orders page has no critical or serious violations', async ({ page }) => {
    await page.goto('/admin/orders');
    await page.waitForLoadState('networkidle');
    await checkA11y(page);
  });
});
