import { test, expect } from '@playwright/test';
import { checkA11y } from '../utils/axe';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Axe checks for authenticated user pages.
 * Requires storage state generated by the E2E setup project.
 * Run `npm run test:e2e --project=setup` once before running a11y checks
 * against authenticated routes, or use the combined CI pipeline which
 * generates storage state automatically.
 */

const AUTH_STATE = path.resolve(__dirname, '../../../tests/.auth/user.json');
const ADMIN_STATE = path.resolve(__dirname, '../../../tests/.auth/admin.json');

test.describe('A11y — Authenticated user pages', () => {
  test.skip(!fs.existsSync(AUTH_STATE), `Missing required auth storage state: ${AUTH_STATE}`);

  test.use({
    storageState: AUTH_STATE,
  });

  test('orders history page has no critical or serious violations', async ({ page }) => {
    await page.goto('/orders');
    await expect(page).toHaveURL('/orders');
    await expect(page.getByRole('heading', { name: 'My Orders' })).toBeVisible();
    await checkA11y(page);
  });

  test('profile page has no critical or serious violations', async ({ page }) => {
    await page.goto('/profile');
    await expect(page).toHaveURL('/profile');
    await expect(page.getByRole('heading', { name: 'Edit Profile' })).toBeVisible();
    await checkA11y(page);
  });
});

test.describe('A11y — Admin pages', () => {
  test.skip(!fs.existsSync(ADMIN_STATE), `Missing required auth storage state: ${ADMIN_STATE}`);

  test.use({
    storageState: ADMIN_STATE,
  });

  test('admin orders page has no critical or serious violations', async ({ page }) => {
    await page.goto('/admin/orders');
    await expect(page).toHaveURL('/admin/orders');
    await expect(page.getByRole('heading', { name: 'Client Orders' })).toBeVisible();
    await checkA11y(page);
  });
});
